name: Testar GitHub Secrets

on:
  workflow_dispatch:  # Permite rodar manualmente pelo GitHub Actions

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir variável secreta
        run: echo "O usuário do banco é ${{ secrets.mongo_user }}"

      - name: Exibir variável secreta (masculando saída)
        run: echo "Senha: [REDACTED]"
